const majors = [
  "Aerospace Engineering",
  "Aeronautics and Astronautics",
  "African American Studies",
  "American Ethnic Studies",
  "American Indian Studies",
  "Anthropology",
  "Anthropology of Globalization",
  "Applied and Computational Mathematical Sciences",
  "Applied Economics and Management",
  "Aquatic and Fishery Sciences",
  "Architectural Design",
  "Architecture",
  "Art",
  "Art History",
  "Asian American and Asian Diaspora Studies",
  "Asian Studies",
  "Astronomy",
  "Astrophysics",
  "Atmospheric Chemistry and Air Quality",
  "Atmospheric Sciences",
  "Biochemical Sciences",
  "Bioengineering",
  "Biology",
  "Biomedical and Health Informatics",
  "Biophysics",
  "Business Administration",
  "Chemical Biology",
  "Chemical Engineering",
  "Chemistry",
  "Chinese",
  "Cinema & Media Studies",
  "Cities, Citizenship, and Migration",
  "Civil Engineering",
  "Classical Studies",
  "Classics",
  "Climate",
  "Communication",
  "Comparative American Ethnic Studies",
  "Comparative History of Ideas",
  "Comparative Religion",
  "Computational Finance and Risk Management",
  "Computer Engineering",
  "Computer Science",
  "Computer Science and Engineering",
  "Construction Management",
  "Creative Studies",
  "Creative Writing",
  "Dance",
  "Dance Studies",
  "Danish",
  "Data Science",
  "Data Sciences and Statistics",
  "Design",
  "Digital Arts and Experimental Media",
  "Disability Studies",
  "Discrete Mathematics and Algorithms",
  "Drama",
  "Earth and Space Sciences",
  "Early Care and Education",
  "Early Childhood and Family Studies",
  "East Asian Studies",
  "Economics",
  "Education Studies",
  "Education, Communities, and Organizations",
  "Electrical Engineering",
  "Engineering and Physical Sciences",
  "English",
  "Environmental Engineering",
  "Environmental Public Health",
  "Environmental Science and Terrestrial Resource Management",
  "Environmental Studies",
  "Ethnic Studies",
  "European Studies",
  "Family and Child Nursing",
  "Film Studies",
  "Finance",
  "Finnish",
  "Food Systems, Nutrition, and Health",
  "French",
  "Gender, Women, and Sexuality Studies",
  "General",
  "Genetics and Plant Biology",
  "Geography",
  "Geology",
  "GeoScience",
  "German Studies",
  "Global Health",
  "Global Literary Studies",
  "Globalization, Health, and Development",
  "Greek",
  "Guitar",
  "Health Education and Promotion",
  "Health Informatics and Health Information Management",
  "History",
  "History of Empire and Colonialism",
  "History of Philosophy",
  "History of Race, Gender, and Power",
  "History of Religion and Society",
  "History of War and Society",
  "Human Centered Design and Engineering",
  "Human Developmental and Regenerative Biology",
  "Human-Computer Interaction",
  "Humanities",
  "Individualized Studies",
  "Indigenous Archaeology",
  "Industrial Design",
  "Industrial Engineering",
  "Informatics",
  "Information Architecture",
  "Information Assurance and Cybersecurity",
  "Information Systems",
  "Integrated Social Sciences",
  "Interaction Design",
  "International Security",
  "Japanese",
  "Jazz Studies",
  "Jewish Studies",
  "Journalism and Public Interest Communication",
  "Korean",
  "Landscape Architecture",
  "Latin",
  "Law, Societies, and Justice",
  "Linguistics",
  "Marine Biology",
  "Materials Science and Engineering",
  "Mathematical Economics and Quantitative Finance",
  "Mathematics",
  "Mechanical Engineering",
  "Mechatronics",
  "Medical Anthropology and Global Health",
  "Medical Laboratory Science",
  "Microbiology",
  "Molecular and Cellular Biology",
  "Molecular, Cellular, and Development",
  "Music",
  "Music Education",
  "Music History",
  "Music Theory",
  "Mythology",
  "Natural Sciences",
  "Near Eastern Culture and Civilization",
  "Near Eastern Languages and Civilization",
  "Neuroscience",
  "Nordic Studies",
  "Norwegian",
  "Nursing",
  "Nutrition",
  "Operations and Supply Chain Management",
  "Organ",
  "Painting and Drawing",
  "Percussion",
  "Performance",
  "Philosophy",
  "Physics",
  "Physiology",
  "Plant",
  "Political Economy",
  "Political Science",
  "Professional Sales",
  "Psychology",
  "Public Health",
  "Quantitative Science",
  "Real Estate",
  "Restoration Ecology and Environmental Horticulture",
  "Romance Linguistics",
  "Russian Language, Literature, and Culture",
  "Scandinavian Studies",
  "Scientific Computing and Numerical Algorithms",
  "Sculpture",
  "Slavic Languages and Literatures",
  "Social Welfare",
  "Social Work",
  "Sociology",
  "South Asian Languages and Literature (Hindi and Sanskrit)",
  "Spanish",
  "Speech and Hearing Sciences",
  "Statistics",
  "Structural Engineering",
  "Sustainable Forest Management",
  "Swedish",
  "Teacher Preparation",
  "Technical Communication",
  "Textiles",
  "Theater, Dance, and Performance Studies",
  "Three Dimensional Forum: Ceramics, Glass, Sculpture",
  "Urban Design and Planning",
  "Urban Studies",
  "Visual Communication Design",
  "Wildlife Conservation",
  "Women and Sexuality Studies",
  "Zoology",
];

export default majors;
