const schools = [
  "Amherst College",
  "Barnard College",
  "Boston College",
  "Boston University",
  "Bowdoin College",
  "Brandeis University",
  "Brown University",
  "California Institute of Technology (Caltech)",
  "Carleton College",
  "Carnegie Mellon University",
  "Case Western Reserve University",
  "Clemson University",
  "Claremont McKenna College",
  "Colby College",
  "Colgate University",
  "Columbia University",
  "Cornell University",
  "Davidson College",
  "Dartmouth College",
  "Duke University",
  "Emory University",
  "Florida State University",
  "Fordham University",
  "George Washington University",
  "Georgetown University",
  "Georgia Institute of Technology",
  "Grinnell College",
  "Hamilton College",
  "Harvard University",
  "Harvey Mudd College",
  "Haverford College",
  "Johns Hopkins University",
  "Kenyon College",
  "Lafayette College",
  "Lehigh University",
  "Macalester College",
  "Massachusetts Institute of Technology (MIT)",
  "Middlebury College",
  "Michigan State University",
  "New York University (NYU)",
  "Northeastern University",
  "Northwestern University",
  "Oberlin College",
  "Ohio State University",
  "Pennsylvania State University",
  "Pepperdine University",
  "Pomona College",
  "Princeton University",
  "Purdue University",
  "Rice University",
  "Rensselaer Polytechnic Institute",
  "Rutgers, The State University of New Jersey",
  "Santa Clara University",
  "Smith College",
  "Southern Methodist University",
  "Stanford University",
  "Stony Brook University",
  "Swarthmore College",
  "Syracuse University",
  "Texas A&M University",
  "Texas Christian University",
  "Tufts University",
  "Tulane University",
  "University of California, Berkeley",
  "University of California, Davis (UCD)",
  "University of California, Irvine (UCI)",
  "University of California, Los Angeles (UCLA)",
  "University of California, Merced (UCM)",
  "University of California, Riverside (UCR)",
  "University of California, San Diego (UCSD)",
  "University of California, Santa Barbara (UCSB)",
  "University of California, Santa Cruz (UCSC)",
  "University of Chicago",
  "University of Florida",
  "University of Georgia",
  "University of Illinois Urbana-Champaign",
  "University of Maryland, College Park",
  "University of Miami",
  "University of Michigan",
  "University of Minnesota Twin Cities",
  "University of North Carolina at Chapel Hill",
  "University of Notre Dame",
  "University of Pennsylvania",
  "University of Pittsburgh",
  "University of Rochester",
  "University of Southern California (USC)",
  "University of Texas at Austin",
  "University of Virginia",
  "University of Washington",
  "University of Wisconsin-Madison",
  "Vanderbilt University",
  "Vassar College",
  "Villanova University",
  "Virginia Tech",
  "Wake Forest University",
  "Washington University in St. Louis",
  "Wellesley College",
  "Wesleyan University",
  "William & Mary",
  "Williams College",
  "Yale University"
];

export default schools;