const schools = [
  "Arizona State University",
  "Baylor University",
  "Boston College",
  "Boston University",
  "Brown University",
  "California Institute of Technology (Caltech)",
  "Carnegie Mellon University",
  "Case Western Reserve University",
  "Clemson University",
  "Columbia University",
  "Dartmouth College",
  "Duke University",
  "Emory University",
  "George Washington University",
  "Georgia Institute of Technology",
  "Harvard University",
  "Indiana University Bloomington",
  "Iowa State University",
  "Johns Hopkins University",
  "Lehigh University",
  "Massachusetts Institute of Technology (MIT)",
  "Michigan State University",
  "New York University (NYU)",
  "Northeastern University",
  "Northwestern University",
  "Ohio State University",
  "Pennsylvania State University",
  "Princeton University",
  "Purdue University",
  "Rensselaer Polytechnic Institute",
  "Rice University",
  "Rutgers, The State University of New Jersey",
  "Stanford University",
  "Stony Brook University",
  "Texas A&M University",
  "Texas Christian University (TCU)",
  "Tufts University",
  "University of Alabama",
  "University of Arizona",
  "University of California, Berkeley",
  "University of California, Davis (UCD)",
  "University of California, Irvine (UCI)",
  "University of California, Los Angeles (UCLA)",
  "University of California, Merced (UCM)",
  "University of California, Riverside (UCR)",
  "University of California, San Diego (UCSD)",
  "University of California, San Francisco (UCSF)",
  "University of California, Santa Barbara (UCSB)",
  "University of California, Santa Cruz (UCSC)",
  "University of Chicago",
  "University of Colorado Boulder",
  "University of Connecticut",
  "University of Delaware",
  "University of Florida",
  "University of Georgia",
  "University of Houston",
  "University of Illinois Chicago (UIC)",
  "University of Illinois Urbana-Champaign",
  "University of Iowa",
  "University of Kansas",
  "University of Kentucky",
  "University of Maryland, College Park",
  "University of Massachusetts Amherst",
  "University of Massachusetts Medical School",
  "University of Miami",
  "University of Michigan",
  "University of Minnesota Twin Cities",
  "University of Nebraska-Lincoln",
  "University of North Carolina at Chapel Hill",
  "University of Notre Dame",
  "University of Oklahoma",
  "University of Oregon",
  "University of Pennsylvania",
  "University of Pittsburgh",
  "University of Rochester",
  "University of South Carolina",
  "University of Southern California (USC)",
  "University of Texas at Austin",
  "University of Texas Dallas",
  "University of Utah",
  "University of Vermont",
  "University of Virginia",
  "University of Washington",
  "University of Wisconsin-Madison",
  "Vanderbilt University",
  "Virginia Tech",
  "Wake Forest University",
  "Washington University in St. Louis",
  "Yale University",
];
 export default schools