const subjectList = [
  "ACT",
  "AP Art History",
  "AP Biology",
  "AP Calculus AB",
  "AP Calculus BC",
  "AP Chemistry",
  "AP Comparative Government and Politics",
  "AP Computer Science A",
  "AP Computer Science Principles",
  "AP Environmental Science",
  "AP European History",
  "AP French Language and Culture",
  "AP German Language and Culture",
  "AP Human Geography",
  "AP Latin",
  "AP Macroeconomics",
  "AP Microeconomics",
  "AP Music Theory",
  "AP Physics 1",
  "AP Physics 2",
  "AP Physics C",
  "AP Psychology",
  "AP Spanish Language and Culture",
  "AP Spanish Literature and Culture",
  "AP Statistics",
  "AP Studio Art: 2-D Design",
  "AP Studio Art: 3-D Design",
  "AP Studio Art: Drawing",
  "AP U.S. Government and Politics",
  "AP U.S. History",
  "AP World History",
  "Algebra 1",
  "Algebra 2",
  "Algorithms",
  "Astronomy",
  "Band",
  "Biology",
  "Calculus",
  "Calculus 1",
  "Calculus 2",
  "Chemistry",
  "Choir",
  "Cognitive Psychology",
  "Comparative Religion",
  "Cultural Anthropology",
  "Creative Writing",
  "Database Management",
  "Data Structures",
  "Differential Equations",
  "Drawing",
  "Drama",
  "Earth Science",
  "Economics",
  "English",
  "English 10",
  "English 11",
  "English 12",
  "English 9",
  "English Composition",
  "Environmental Science",
  "Environmental Studies",
  "Ethics",
  "Finance",
  "French 1",
  "French 2",
  "Geography",
  "Geometry",
  "German 1",
  "German 2",
  "Global Politics",
  "Government",
  "Health Education",
  "International Economics",
  "International Relations",
  "Introduction to Computer Science",
  "Introduction to Philosophy",
  "Introduction to Psychology",
  "Linear Algebra",
  "Logic",
  "Macroeconomics",
  "Management",
  "Marketing",
  "Mathematics",
  "Microeconomics",
  "Multivariable Calculus",
  "Music",
  "Natural Sciences",
  "Orchestra",
  "Organic Chemistry",
  "Painting",
  "Performing Arts",
  "Philosophy",
  "Photography",
  "Physical Education",
  "Physics",
  "Plant",
  "Political Economy",
  "Political Science",
  "Pre-Calculus",
  "Programming in Python",
  "Psychology",
  "Quantum Physics",
  "Real Estate",
  "SAT",
  "Science",
  "Sculpture",
  "Sociology",
  "Spanish 1",
  "Spanish 2",
  "Spanish 3",
  "Spanish 4",
  "Statistics",
  "Trigonometry",
  "U.S. History",
  "Web Development",
  "World History",
  "World Literature",
  "Writing",
  "Zoology",
];

export default subjectList;
